language: node_js
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - node

addons:
  sonarcloud:
    organization: "alfdocimo-github" # the key of the org you chose at step #3
    token:
      secure: SONAR_TOKEN

install:
  - yarn

script:
  - yarn test
  - sonar-scanner -D"sonar.projectKey=alfdocimo_rondel" -D"sonar.organization=alfdocimo-github" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=${SONAR_TOKEN}"
  - yarn prepare
